<?php
/**
 * Created by PhpStorm.
 * User: apple
 * Date: 16/3/15
 * Time: PM3:34
 */

namespace SpiderManager\Src;


class FileHandle extends HttpHandle
{
    /**
     * @override
     */
    public function CheckUserAgent()
    {
        parent::CheckUserAgent(); // TODO: Change the autogenerated stub
    }
    /**
     * @override
     */
    public function WriteMessage()
    {
        parent::WriteMessage(); // TODO: Change the autogenerated stub
    }
    /**
     * @override
     */
    public function ConfirmMessage()
    {
        parent::ConfirmMessage(); // TODO: Change the autogenerated stub
    }
}